### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by christina-ml** [pursuit-employment/Pursuit-Code-Challenges#6]
### Description
Open source isn't only about writing code - documentation is just as important. It's a great way to get familiar with the code base and the project itself.

There should be some documentation for this Open Source repo.
Check out [Open Source Guide](https://opensource.guide/starting-a-project/) `Section 3: Launching your own open source project`.

### Tasks
This project should include the following documentation:
- [ ] [Open source license](https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository)
- [x] [README](https://help.github.com/articles/create-a-repo/#commit-your-first-change)
- [ ] [Contributing guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
- [ ] [Code of conduct](https://opensource.guide/code-of-conduct/)

Since there is more than one task, Multiple contributors can work on this issue.
